site_name: Uniform Engine Docs
theme:
  name: material
  palette:
    # Dark mode first
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # Light mode second
    - scheme: light
      primary: green
      accent: light green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
